server:
  port: 8000
spring:
  profiles:
    active: prod
    include: feign
  application:
    name: service-order
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        namespace: test    #指定 Nacos 的命名空间



  config:
    import:
      - nacos:common.yml?group=order      # 指定 Nacos 的 DataId和group
      - nacos:database.yml?group=order    # 指定 Nacos 的 DataId和group



order:
  timeout: 60min
  await-time: 10d

logging:
  level:
    com.atguigu.order.feign: debug
